CREATE TABLE parametro (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    host VARCHAR(50) NULL,
	usuario VARCHAR(50) NULL,
	senha VARCHAR(50) NULL,
	comissao INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
