CREATE TABLE banco (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO banco (nome) VALUES ('001 - BANCO DO BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('003 - BANCO DA AMAZONIA S.A.');
INSERT INTO banco (nome) VALUES ('004 - BANCO DO NORDESTE DO BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('021 - BANESTES S.A BANCO DO ESTADO DO ESPIRITO SANTO');
INSERT INTO banco (nome) VALUES ('024 - BANCO DE PERNAMBUCO S.A.-BANDEPE');
INSERT INTO banco (nome) VALUES ('025 - BANCO ALFA S/A');
INSERT INTO banco (nome) VALUES ('027 - BANCO DO ESTADO DE SANTA CATARINA S.A.');
INSERT INTO banco (nome) VALUES ('029 - BANCO BANERJ S.A.');
INSERT INTO banco (nome) VALUES ('031 - BANCO BEG S.A.');
INSERT INTO banco (nome) VALUES ('033 - BANCO SANTANDER S.A.');
INSERT INTO banco (nome) VALUES ('034 - BANCO DO ESTADO DO AMAZONAS S.A.');
INSERT INTO banco (nome) VALUES ('036 - BANCO BRADESCO BBI S.A.');
INSERT INTO banco (nome) VALUES ('037 - BANCO DO ESTADO DO PARA S.A.');
INSERT INTO banco (nome) VALUES ('038 - BANCO BANESTADO S.A.');
INSERT INTO banco (nome) VALUES ('039 - BANCO DO ESTADO DO PIAUI S.A. - BEP');
INSERT INTO banco (nome) VALUES ('040 - BANCO CARGILL S.A');
INSERT INTO banco (nome) VALUES ('041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.');
INSERT INTO banco (nome) VALUES ('044 - BANCO BVA SA');
INSERT INTO banco (nome) VALUES ('045 - BANCO OPPORTUNITY S.A.');
INSERT INTO banco (nome) VALUES ('047 - BANCO DO ESTADO DE SERGIPE S.A.');
INSERT INTO banco (nome) VALUES ('062 - HIPERCARD BANCO MÚLTIPLO S.A');
INSERT INTO banco (nome) VALUES ('063 - BANCO IBI S.A - BANCO MULTIPLO');
INSERT INTO banco (nome) VALUES ('065 - LEMON BANK BANCO MÚLTIPLO S..A');
INSERT INTO banco (nome) VALUES ('066 - BANCO MORGAN STANLEY S.A');
INSERT INTO banco (nome) VALUES ('069 - BPN BRASIL BANCO MÚLTIPLO S.A.');
INSERT INTO banco (nome) VALUES ('070 - BRB - BANCO DE BRASILIA S.A.');
INSERT INTO banco (nome) VALUES ('072 - BANCO RURAL MAIS S.A.');
INSERT INTO banco (nome) VALUES ('073 - BB BANCO POPULAR DO BRASL S.A.'); 
INSERT INTO banco (nome) VALUES ('074 - BANCO J.SAFRA S.A.');
INSERT INTO banco (nome) VALUES ('075 - BANCO CR2 S.A.');
INSERT INTO banco (nome) VALUES ('076 - BANCO KDB DO BRASIL S.A.'); 
INSERT INTO banco (nome) VALUES ('096 - BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.');
INSERT INTO banco (nome) VALUES ('116 - BANCO ÚNICO S.A.');
INSERT INTO banco (nome) VALUES ('151 - BANCO NOSSA CAIXA S.A');
INSERT INTO banco (nome) VALUES ('175 - BANCO FINASA S.A.');
INSERT INTO banco (nome) VALUES ('184 - BANCO ITAÚ - BBA S.A.');
INSERT INTO banco (nome) VALUES ('204 - BANCO BRADESCO CARTÕES S.A');
INSERT INTO banco (nome) VALUES ('208 - BANCO UBS PACTUAL S.A.');
INSERT INTO banco (nome) VALUES ('212 - BANCO MATONE S.A.');
INSERT INTO banco (nome) VALUES ('213 - BANCO ARBI S.A.');
INSERT INTO banco (nome) VALUES ('214 - BANCO DIBENS S.A.');
INSERT INTO banco (nome) VALUES ('215 - BANCO ACOMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.');
INSERT INTO banco (nome) VALUES ('217 - BANCO JOHN DEERE S.A.');
INSERT INTO banco (nome) VALUES ('218 - BANCO BONSUCESSO S.A.');
INSERT INTO banco (nome) VALUES ('222 - BANCO CLAYON BRASIL S/A');
INSERT INTO banco (nome) VALUES ('224 - BANCO FIBRA S.A.');
INSERT INTO banco (nome) VALUES ('225 - BANCO BRASCAN S.A.');
INSERT INTO banco (nome) VALUES ('229 - BANCO CRUZEIRO DO SUL S.A.');
INSERT INTO banco (nome) VALUES ('230 - UNICARD BANCO MÚLTIPLO S.A.');
INSERT INTO banco (nome) VALUES ('233 - BANCO GE CAPITAL S.A');
INSERT INTO banco (nome) VALUES ('237 - BANCO BRADESCO S.A.');
INSERT INTO banco (nome) VALUES ('241 - BANCO CLASSICO S.A.');
INSERT INTO banco (nome) VALUES ('243 - BANCO MAXIMA S.A.');
INSERT INTO banco (nome) VALUES ('246 - BANCO ABC-BRASIL S.A');
INSERT INTO banco (nome) VALUES ('248 - BANCO BOAVISTA INTERATLANTICO S.A.'); 
INSERT INTO banco (nome) VALUES ('249 - BANCO INVESTCRED UNIBANCO S.A.');
INSERT INTO banco (nome) VALUES ('250 - BANCO SCHAHIN');
INSERT INTO banco (nome) VALUES ('252 - BANCO FININVEST S.A.');
INSERT INTO banco (nome) VALUES ('254 - PARANÁ BANCO S.A.');
INSERT INTO banco (nome) VALUES ('263 - BANCO CACIQUE S.A.');
INSERT INTO banco (nome) VALUES ('265 - BANCO FATOR S.A.');
INSERT INTO banco (nome) VALUES ('266 - BANCO CEDULA S.A.');
INSERT INTO banco (nome) VALUES ('300 - BANCO DE LA NACION ARGENTINA');
INSERT INTO banco (nome) VALUES ('318 - BANCO BMG S.A.');
INSERT INTO banco (nome) VALUES ('320 - BANCO INDUSTRIAL E COMERCIAL S.A.');
INSERT INTO banco (nome) VALUES ('341 - BANCO ITAU S.A.');
INSERT INTO banco (nome) VALUES ('356 - BANCO ABN AMRO REAL S.A.');
INSERT INTO banco (nome) VALUES ('366 - BANCO SOCIETE GENERALE BRASIL S.A');
INSERT INTO banco (nome) VALUES ('370 - BANCO WESTLB DO BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('376 - BANCO J.P. MORGAN S.A.');
INSERT INTO banco (nome) VALUES ('389 - BANCO MERCANTIL DO BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('394 - BANCO BMC S.A.');
INSERT INTO banco (nome) VALUES ('399 - HSBC BANK BRASIL S.A.-BANCO MULTIPLO');
INSERT INTO banco (nome) VALUES ('409 - UNIBANCO - UNIAO DE BANCOS BRASILEIROS S.A.');
INSERT INTO banco (nome) VALUES ('412 - BANCO CAPITAL S.A.');
INSERT INTO banco (nome) VALUES ('422 - BANCO SAFRA S.A.');
INSERT INTO banco (nome) VALUES ('453 - BANCO RURAL S.A.');
INSERT INTO banco (nome) VALUES ('456 - BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('464 - BANCO SUMITOMO MITSUI BRASILEIRO S.A.');
INSERT INTO banco (nome) VALUES ('477 - CITIBANK N.A.');
INSERT INTO banco (nome) VALUES ('479 - BANCO ITAUBANK S.A.');
INSERT INTO banco (nome) VALUES ('487 - DEUTSCHE BANK S. A. - BANCO ALEMAO');
INSERT INTO banco (nome) VALUES ('488 - JPMORGAN CHASE BANK, NATIONAL ASSOCIATION');
INSERT INTO banco (nome) VALUES ('492 - ING BANK N.V.');
INSERT INTO banco (nome) VALUES ('494 - BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY');
INSERT INTO banco (nome) VALUES ('495 - BANCO DE LA PROVINCIA DE BUENOS AIRES');
INSERT INTO banco (nome) VALUES ('505 - BANCO CREDIT SUISSE (BRASIL) S.A.');
INSERT INTO banco (nome) VALUES ('600 - BANCO LUSO BRASILEIRO S.A.');
INSERT INTO banco (nome) VALUES ('604 - BANCO INDUSTRIAL DO BRASIL S. A.');
INSERT INTO banco (nome) VALUES ('610 - BANCO VR S.A.');
INSERT INTO banco (nome) VALUES ('611 - BANCO PAULISTA S.A.');
INSERT INTO banco (nome) VALUES ('612 - BANCO GUANABARA S.A.');
INSERT INTO banco (nome) VALUES ('613 - BANCO PECUNIA S.A.');
INSERT INTO banco (nome) VALUES ('623 - BANCO PANAMERICANO S.A.');
INSERT INTO banco (nome) VALUES ('626 - BANCO FICSA S.A.');
INSERT INTO banco (nome) VALUES ('630 - BANCO INTERCAP S.A.');
INSERT INTO banco (nome) VALUES ('633 - BANCO RENDIMENTO S.A.');
INSERT INTO banco (nome) VALUES ('634 - BANCO TRIANGULO S.A.');
INSERT INTO banco (nome) VALUES ('637 - BANCO SOFISA S.A.');
INSERT INTO banco (nome) VALUES ('638 - BANCO PROSPER S.A.');
INSERT INTO banco (nome) VALUES ('641 - BANCO ALVORADA S.A');
INSERT INTO banco (nome) VALUES ('643 - BANCO PINE S.A.');
INSERT INTO banco (nome) VALUES ('652 - BANCO ITAÚ HOLDING FINANCEIRA S.A.');
INSERT INTO banco (nome) VALUES ('653 - BANCO INDUSVAL S.A.');
INSERT INTO banco (nome) VALUES ('654 - BANCO A.J. RENNER S.A.');
INSERT INTO banco (nome) VALUES ('655 - BANCO VOTORANTIM S.A.');
INSERT INTO banco (nome) VALUES ('707 - BANCO DAYCOVAL S.A.');
INSERT INTO banco (nome) VALUES ('719 - BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A.');
INSERT INTO banco (nome) VALUES ('721 - BANCO CREDIBEL S.A.');
INSERT INTO banco (nome) VALUES ('734 - BANCO GERDAU S.A.');
INSERT INTO banco (nome) VALUES ('735 - BANCO POTTENCIAL S.A.');
INSERT INTO banco (nome) VALUES ('738 - BANCO MORADA S.A.');
INSERT INTO banco (nome) VALUES ('739 - BANCO BGN S.A.');
INSERT INTO banco (nome) VALUES ('740 - BANCO BARCLAYS S.A.');
INSERT INTO banco (nome) VALUES ('741 - BANCO RIBEIRAO PRETO S.A.');
INSERT INTO banco (nome) VALUES ('743 - BANCO SEMEAR S.A.');
INSERT INTO banco (nome) VALUES ('744 - BANKBOSTON N.A.');
INSERT INTO banco (nome) VALUES ('745 - BANCO CITIBANK S.A.');
INSERT INTO banco (nome) VALUES ('746 - BANCO MODAL S.A.');
INSERT INTO banco (nome) VALUES ('747 - BANCO RABOBANK INTERNATIONAL BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('748 - BANCO COOPERATIVO SICREDI S.A.');
INSERT INTO banco (nome) VALUES ('749 - BANCO SIMPLES S.A.');
INSERT INTO banco (nome) VALUES ('751 - DRESDNER BANK BRASIL S.A. BANCO MULTIPLO.');
INSERT INTO banco (nome) VALUES ('752 - BANCO BNP PARIBAS BRASIL S.A.');
INSERT INTO banco (nome) VALUES ('753 - BANCO COMERCIAL URUGUAI S.A.');
INSERT INTO banco (nome) VALUES ('756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB');
INSERT INTO banco (nome) VALUES ('757 - BANCO KEB DO BRASIL S.A.');

CREATE TABLE usuario (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    telefone VARCHAR(20),
    cpf VARCHAR(30),
    rg VARCHAR(30),
    senha VARCHAR(120) NOT NULL,
    ativo BOOLEAN DEFAULT true,
    data_nascimento DATE,
    logradouro VARCHAR(50),
    numero VARCHAR(15),
    complemento VARCHAR(20),
    bairro VARCHAR(50),
    cep VARCHAR(15),
    cidade VARCHAR(50),
    estado VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE grupo (
    codigo BIGINT(20) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE permissao (
    codigo BIGINT(20) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE usuario_grupo (
    codigo_usuario BIGINT(20) NOT NULL,
    codigo_grupo BIGINT(20) NOT NULL,
    PRIMARY KEY (codigo_usuario, codigo_grupo),
    FOREIGN KEY (codigo_usuario) REFERENCES usuario(codigo),
    FOREIGN KEY (codigo_grupo) REFERENCES grupo(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE grupo_permissao (
    codigo_grupo BIGINT(20) NOT NULL,
    codigo_permissao BIGINT(20) NOT NULL,
    PRIMARY KEY (codigo_grupo, codigo_permissao),
    FOREIGN KEY (codigo_grupo) REFERENCES grupo(codigo),
    FOREIGN KEY (codigo_permissao) REFERENCES permissao(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE conta_bancaria (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    banco VARCHAR(80) NOT NULL,
    agencia VARCHAR(10) NOT NULL,
    conta VARCHAR(10) NOT NULL,
    principal BOOLEAN DEFAULT true,
    codigo_usuario BIGINT(20)NOT NULL,
    FOREIGN KEY (codigo_usuario) REFERENCES usuario(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
